name: RPGTools
version: '1.0.0'
main: org.shyni.RPGTools.RPGTools
api-version: '1.21'
authors: [ Shyni ]
description: Plugin that allows leveling tools!


commands:
#  command:
#    description: "this is a command"
#    usage: "/command <arg>"
#    aliases: [ cmd, command ]
#    permission: permission.node
#    permission-message: "You do not have permission to use this command"
  rpgtools:
    description: "rpgtools command"
    usage: "/rpgtools [givexp/levelup] [<amount>]"
    permission: rpgtools.admin

permissions:
#  permission.node:
#    description: "this is a permission node"
#    default: op
#    children:
#      permission.node.child: true
#  another.permission.node:
#    description: "this is another description"
#    default: not op