# Maximum level for a tool only whole numbers (e.g 5, 12, 21, 25, 100)
# default = 20
max-level: 20
# XP multiplier only whole numbers (e.g 5, 12, 21, 25, 100)
# default = 1
default-xp-multiplier: 1


# input any enchantment from the following list: https://jd.papermc.io/paper/1.21.5/org/bukkit/enchantments/Enchantment.html
Level_Enchantments:
  PICKAXE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  SHOVEL:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  AXE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  HOE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  SWORD:
    1:
    2:
    3:
    4:
    5:
    6:
    7:
    8:
    9:
    10:

## XP for mob kill
Mobs:
  #PASSIVE MOBS
  ALLAY: 1
  ARMADILLO: 1
  AXOLOTL: 1
  BAT: 0
  CAMEL: 1
  CAT: 1
  CHICKEN: 1
  COD: 0
  COW: 1
  DONKEY: 1
  FROG: 1
  GLOW_SQUID: 1
  HORSE: 1
  OCELOT: 1
  PARROT: 0
  PIG: 1
  PUFFERFISH: 0
  RABBIT: 0
  SALMON: 0
  SHEEP: 1
  SKELETON_HORSE: 2
  SNIFFER: 1
  SNOW_GOLEM: 1
  SQUID: 1
  STRIDER: 1
  TADPOLE: 0
  TROPICAL_FISH: 0
  TURTLE: 1
  VILLAGER: 0
  WANDERING_TRADER: 0
  #NEUTRAL MOBS
  BEE: 1
  CAVE_SPIDER: 1
  DOLPHIN: 1
  DROWNED: 1
  ENDERMAN: 3
  FOX: 2
  GOAT: 2
  IRON_GOLEM: 5
  LLAMA: 2
  PANDA: 2
  PIGLIN: 1
  POLAR_BEAR: 5
  SPIDER: 1
  TRADER_LLAMA: 1
  WOLF: 2
  ZOMBIFIED_PIGLIN: 1
  #HOSTILE MOBS
  BLAZE: 3
  BOGGED: 2
  BREEZE: 10
  CREAKING: 5
  CREEPER: 4
  ELDER_GUARDIAN: 5
  ENDERMITE: 1
  EVOKER: 10
  GHAST: 5
  GUARDIAN: 5
  HOGLIN: 1
  HUSK: 1
  MAGMA_CUBE: 2
  PHANTOM: 1
  PIGLIN_BRUTE: 1
  PILLAGER: 3
  RAVAGER: 10
  SHULKER: 3
  SILVERFISH: 1
  SKELETON: 4
  SLIME: 1
  STRAY: 1
  VEX: 1
  VINDICATOR: 1
  WARDEN: 100
  WITCH: 10
  WITHER_SKELETON: 5
  ZOGLIN: 2
  ZOMBIE: 2
  ZOMBIE_VILLAGER: 1

  #BOSSES
  ENDER_DRAGON: 250
  WITHER: 200