# Maximum level for a tool only whole numbers (e.g 5, 12, 21, 25, 100)
# default = 20
max-level: 20
# XP multiplier only whole numbers (e.g 5, 12, 21, 25, 100)
# default = 1
default-xp-multiplier: 1


# input any enchantment from the following list: https://jd.papermc.io/paper/1.21.5/org/bukkit/enchantments/Enchantment.html
Level_Enchantments:
  PICKAXE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  SHOVEL:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  AXE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  HOE:
    1:
      EFFICIENCY: 1
    2:
      EFFICIENCY: 1
      UNBREAKING: 1
    3:
      EFFICIENCY: 1
      UNBREAKING: 1
      FORTUNE: 1
    4:
      EFFICIENCY: 2
      UNBREAKING: 1
      FORTUNE: 1
    5:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 1
    6:
      EFFICIENCY: 2
      UNBREAKING: 2
      FORTUNE: 2
    7:
      EFFICIENCY: 3
      UNBREAKING: 2
      FORTUNE: 2
    8:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 2
    9:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
    10:
      EFFICIENCY: 3
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    11:
      EFFICIENCY: 4
      UNBREAKING: 3
      FORTUNE: 3
      MENDING: 1
    12:
      EFFICIENCY: 4
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    13:
      EFFICIENCY: 5
      UNBREAKING: 4
      FORTUNE: 3
      MENDING: 1
    14:
      EFFICIENCY: 5
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    15:
      EFFICIENCY: 6
      UNBREAKING: 5
      FORTUNE: 3
      MENDING: 1
    16:
      EFFICIENCY: 6
      UNBREAKING: 6
      FORTUNE: 4
      MENDING: 1
    17:
      EFFICIENCY: 7
      UNBREAKING: 7
      FORTUNE: 4
      MENDING: 1
    18:
      EFFICIENCY: 8
      UNBREAKING: 8
      FORTUNE: 4
      MENDING: 1
    19:
      EFFICIENCY: 9
      UNBREAKING: 9
      FORTUNE: 4
      MENDING: 1
    20:
      EFFICIENCY: 10
      UNBREAKING: 10
      FORTUNE: 5
      MENDING: 1
  SWORD:
    1:
      SHARPNESS: 1
    2:
      SHARPNESS: 2
    3:
      UNBREAKING: 1
    4:
    5:
    6:
    7:
    8:
    9:
    10:

## XP for mob kill
Mobs:
  #PASSIVE MOBS
  ALLAY: 5
  ARMADILLO: 5
  AXOLOTL: 5
  BAT: 1
  CAMEL: 5
  CAT: 1
  CHICKEN: 1
  COD: 1
  COW: 5
  DONKEY: 5
  FROG: 2
  GLOW_SQUID: 3
  HORSE: 5
  OCELOT: 1
  PARROT: 1
  PIG: 5
  PUFFERFISH: 1
  RABBIT: 1
  SALMON: 1
  SHEEP: 5
  SKELETON_HORSE: 10
  SNIFFER: 5
  SNOW_GOLEM: 5
  SQUID: 2
  STRIDER: 3
  TADPOLE: 1
  TROPICAL_FISH: 1
  TURTLE: 3
  VILLAGER: 0
  WANDERING_TRADER: 0
  #NEUTRAL MOBS
  BEE: 1
  CAVE_SPIDER: 3
  DOLPHIN: 3
  DROWNED: 10
  ENDERMAN: 15
  FOX: 3
  GOAT: 3
  IRON_GOLEM: 20
  LLAMA: 5
  PANDA: 5
  PIGLIN: 5
  POLAR_BEAR: 10
  SPIDER: 5
  TRADER_LLAMA: 5
  WOLF: 5
  ZOMBIFIED_PIGLIN: 5
  #HOSTILE MOBS
  BLAZE: 10
  BOGGED: 10
  BREEZE: 10
  CREAKING: 20
  CREEPER: 5
  ELDER_GUARDIAN: 25
  ENDERMITE: 1
  EVOKER: 15
  GHAST: 20
  GUARDIAN: 10
  HOGLIN: 5
  HUSK: 5
  MAGMA_CUBE: 1
  PHANTOM: 5
  PIGLIN_BRUTE: 15
  PILLAGER: 5
  RAVAGER: 20
  SHULKER: 5
  SILVERFISH: 1
  SKELETON: 5
  SLIME: 1
  STRAY: 5
  VEX: 1
  VINDICATOR: 15
  WARDEN: 100
  WITCH: 20
  WITHER_SKELETON: 10
  ZOGLIN: 10
  ZOMBIE: 5
  ZOMBIE_VILLAGER: 5

  #BOSSES
  ENDER_DRAGON: 250
  WITHER: 200